Module7 task1
htmlacademy-univer-javascript-1/2433145-kekstagram-4 pull request #7
Opened 2023-11-03 17:53 UTC by Emma-Shifter

2023-11-03 18:01 UTC, Emma-Shifter commented
исправила ошибки eslint, файлом main.js мы по факту не пользуемся

2023-11-13 11:13 UTC, Safyann requested changes

2023-11-13 11:13 UTC, Safyann commented on index.html
> +  <script src="js/draw.js" type="module"></script>
давай все подключать в main.js, удали

2023-11-13 11:13 UTC, Safyann commented on js/draw.js
> +    newElem.children[0].alt = photo.description;
давай распишем через querySelector, а то не понятно что есть children[0], children[1]

2023-11-13 11:13 UTC, Safyann commented on js/main.js
> -import './generate.js';
импортировать drawSmall

2023-11-13 12:00 UTC, merged